### ISSUE TITLE
Develop research plan for engagement discovery

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#10]
Design a research plan that achieves the following: 
<img width="520" alt="screen shot 2018-10-22 at 12 53 32 pm" src="https://user-images.githubusercontent.com/1305629/47306046-52f28a80-d5f9-11e8-93bf-363d6071da24.png">

- [x] Figure out approval process (if there is one) for conducting user research beyond VT staff
- [x] Identify who to talk to about highest-priority modules
- [x] Schedule conversations
- [x] Share with Cass for discussion
- [x] Early conversations with Sean, Thani and Kenan

**Comment by amyashida** [comment]
Yes and no. I need to go over what Amy sent and ask a few more questions. I have a better idea of it, but it isn't completely clear that there is a specific approval process. The biggest hurdle seems to be getting permission from Vermonters. 

This is half done I suppose.
