### ISSUE TITLE
Set prototype up with continuous integration and deployment tools

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#12]
Continue to model CI/CD workflows with ADS in order to probe on what is possible within the current environment and identify possible barriers to continuous integration and deployment.

Concrete next steps: 

- [ ] Code Climate
- [ ] CircleCI
- [ ] Snyk
- [ ] Possibly azure deployment
- [ ] Discuss how VT/18F/C2 prefer to approach this

**Comment by stvnrlly** [comment]
I think this is somewhat blocked while we (1) research the auth tool we want to use (see #25), (2) figure out the Azure/GitHub workflow, and (3) get the right permissions for the deploy environment.

**Comment by arouault** [comment]
Superceded by QASP training. Closing.
