### ISSUE TITLE
Determine path forward for Quality Assurance Plan

### ISSUE THREAD

**Issue by randyhart** [VermontAHS/IEE-Modernization#18]
**Goal**: 
Help develop vendor management best practices through the exploration of a possible Quality Assurance Surveillance Plan to the work that Nava is doing.

**Successful if**:
- [x] Dixie and Randy have a common understanding of purpose of QASP
- [x] Dixie and Randy have a plan for bringing other important stakeholders into the conversation
- [x] There is a path forward for introducing the QASP to the project

**Concrete Next Steps**:
- [x] Schedule meeting with Dixie and Randy - stvn and Alicia as optional
- [x] Re-share draft QASP with Dixie
- [x] Determine who needs to be in follow up meeting with broader team
- [x] Schedule meeting

**Comment by randyhart** [comment]
@stvnrlly I believe this issue is complete. Dixie set up a meeting with us and the necessary Vermont staff to discuss the path forward during the week of Thanksgiving.

**Comment by randyhart** [comment]
On Thursday, November 15, Dixie sent the final draft QASP to the broader product team for discussion at next Monday's meeting.

**Comment by stvnrlly** [comment]
Great stuff! Thanks, Randy.
