### ISSUE TITLE
Tech sessions for 18F Staff with Steven 

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#21]
Goal: Get 18F team up to speed on specific technical topics re: VT 

Measures of Success:
- [x] Topics are relevant to VT 

Next Steps: 
- [x] Define technical topics
- [x] Plan and schedule tech sessions to get 18F team & VT staff up to speed on concepts

**Comment by stvnrlly** [comment]
There's desire to expand this to VT staff, as well.

**Comment by stvnrlly** [comment]
We have our first two topics on the calendar: an overview of security standards and a demonstration of a continuous integration, continuous delivery pipeline.
