### ISSUE TITLE
Paper Application Workshop Artifacts

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#28]
Answer the following questions:

**- What is our goal / what are we trying to accomplish in the next 2 weeks?**

- Refine useful artifacts post workshop 
- Ensure there are clear next steps for the team  

**- How will we measure if this is successful (Acceptance Criteria)?**
- [x] artifact can/will lead to a next step 
- [x] guide VT staff toward action

**- What are the Concrete Next Steps?**

- [x] refining fidelity of Customer map 
- [x] time to discuss with Product team 
- [x] gain clarity on next steps for State journeymap / follow up on Belaji work 
- [x] digitize highlights, share with PO and Cass, Thani
 
- Add to Project Board in Flight
- Apply any appropriate labels

**Comment by amyashida** [comment]
Digital versions of the journey maps are here: https://app.mural.co/t/gsa6/m/gsa6/1540818694321/aaac87704c79b4cff27066f19581fb3cccaaf141

**Comment by arouault** [comment]
Next Steps meeting being scheduled for week of 11/26

**Comment by arouault** [comment]
@arouault Add any images of takeaways

**Comment by amyashida** [comment]
Takeaways here: https://app.mural.co/t/gsa6/m/gsa6/1542819117010/53837f43ef093b0ef97e7686f70677513d19b98d

**Comment by arouault** [comment]
Amy to work with Etiane directly on this moving forward.
