### ISSUE TITLE
Offer Initial resources VT on technical recruitment 

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#30]
**Goal:** 
- support VT staff in developing an improved recruitment strategy for developers 

**Success Criteria:** 
- provide actionable advice 

**next steps:** 

- [x]  Get a hold of their existing job description
- [x]  Offer feedback to Marcia/Seamus 
- [x] Connect VT to CfA talent 
- [x] Talk to our 18F talent team 
- [x] find and share 18F job descriptions that have been successful

**Comment by arouault** [comment]
Existing job descriptions are here: https://github.com/VermontAHS/IEE-Modernization/issues/21

**Comment by arouault** [comment]
Updates on Talent Team: 

- 18F talent suggests looks at Join TTS 
- Cass was already connected to CfA Talent team by Laura Ponce directly.

**Comment by stvnrlly** [comment]
Here's a list of 18F position descriptions: https://github.com/18F/18f.gsa.gov/tree/master/_join/open-positions

**Comment by stvnrlly** [comment]
And here is the TTS version: https://github.com/18F/join.tts.gsa.gov/tree/master/pages/positions

**Comment by arouault** [comment]
Seamus: Hired someone! We are receiving resumes.

**Comment by arouault** [comment]
- [ ] Identifying areas of work for web developers to own, given budget constraints

**Comment by arouault** [comment]
No more immediate action.
