### ISSUE TITLE
Get SharePoint access for 18F

### ISSUE THREAD

**Issue by stvnrlly** [VermontAHS/IEE-Modernization#35]
Answer the following questions:

**- What is our goal / what are we trying to accomplish in the next 2 weeks?**

**- How will we measure if this is successful (Acceptance Criteria)?**

**- What are the Concrete Next Steps?**

Then: 
- Assign a Lead to this Work
- Add to Project Board in Flight
- Apply any appropriate labels

**Comment by stvnrlly** [comment]
Apparently this is not possible. We'll need to find a different way to collaborate on documents.

**Comment by arouault** [comment]
Apparently this *is* possible. Traci is putting in a ticket request to obtain access for 18F.

**Comment by arouault** [comment]
All set. Please address the email to complete this by calling IT.
