### ISSUE TITLE
Customer Portal Phase 2 Visioning

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#36]
Goal: Refine and Publish Vision for Customer Portal Phase 2 

Acceptance Criteria: 
- [x] vision is clear
- [x] - contains a north star (refer to #32)
- [x] - contains a clear problem statement 
- [x] - breaks a large module into manageable chunks 
- [x] - considers technical and budgetary constraints
- [x] - vision is created collaboratively by business and ADS 
- [x] - useful for CMS communications
- [x] - positioned as a foundation for roadmap work

Next Steps: 
- [x]  hold working session with Thani, Bob, ADS and relevant business staff 
- [x]  hold "magic wand' session with Business staff
- [x]  hold meeting to consider known constraints 
- [x]  document draft and send to Cass
- [x]  Cass reviews - submit to CMS

**Comment by arouault** [comment]
- [ ] prioritize for CMS 
- [ ] North star work and user research should occur separately

**Comment by arouault** [comment]
Need to align with Cass/Thani on the plan on Monday/Tuesday.

**Comment by amyashida** [comment]
- [ ] Review alignment between mitigation requirements and previously brainstormed functionality

Documented here: https://app.mural.co/t/gsa6/m/gsa6/1542987740955/d9ac39214734e63baa164b7181eb8b6409093451

**Comment by arouault** [comment]
CMS draft here https://docs.google.com/presentation/d/1B-eGU6lyDA8YNhb2jMkPBJ6sFYIpNlB34zQfW7sbZ_M/edit?usp=drive_web&ouid=114410930609250902809

Awaiting review by Cass.

**Comment by arouault** [comment]
Cass provided her edits, Addie and Policy chimed in. This is ready to close.
