### ISSUE TITLE
Add all workshop artifacts and public summary to github 

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#8]
Document the October workshop publicly, ensure all artifacts are linked on github.

**Comment by arouault** [comment]
Randy's current state journey map is here: https://app.mural.co/t/nava4113/m/nava4113/1539180761392/1d76b180583ab580b2ccd49acce205bc2fb48ee5

All other assets are documented here: 
https://app.mural.co/t/gsa6/m/gsa6/1539872979181/ff3ebae672b613dfd21a767551412368b034cf6d

**Comment by arouault** [comment]
from Amy: Also need to make sure the prototypes are linked to in the takeaways doc.

**Comment by arouault** [comment]
Here's the repo where it should live. https://github.com/VermontAHS/Authentication-Workshop

**Comment by amyashida** [comment]
Repo has been updated and reviewed.

**Comment by arouault** [comment]
All set.
