### ISSUE TITLE
Design workshop session for HCAU war room: Nov 8

### ISSUE THREAD

**Issue by arouault** [VermontAHS/IEE-Modernization#9]
Design workshop sessions for HCAU war room on November 8th. 

Draft Agenda 
[HCAU War Room Plan_Operational Readiness.docx](https://github.com/VermontAHS/IEE-Modernization/files/2502264/HCAU.War.Room.Plan_Operational.Readiness.docx)

**Comment by arouault** [comment]
18F's section may shift to a different format, led by Amy Marshall-Cerny. Need to confirm that with the HCAU Paper App team.

**Comment by arouault** [comment]
Update: Amy and Alicia will travel to VT on Nov 8th to facilitate. @amyashida to deliver a more fleshed out journey mapping exercise to Chelsea and Thani by Oct 31.

**Comment by amyashida** [comment]
Here is what I have put together so far: 

Description: 
https://docs.google.com/document/d/1Hpihcusyv3HmB5BUH5HcADBQ1aE5erkYIXpO_76DxQM/edit#

Mapping templates: 
https://app.mural.co/t/gsa6/m/gsa6/1540818694321/aaac87704c79b4cff27066f19581fb3cccaaf141

**Comment by arouault** [comment]
This looks great. @amyashida Added some minor changes to the write up. Should we also propose an introduction to the format as part of this? I think walking through folks on what to expect / adopting "beginner's mindset" will be important. Thani wants to intro the purpose of the exercise beforehand.
